[package]
name = "shazamrs"
version = "0.1.0"
edition = "2024"

[[example]]
name = "recognize-song"
path = "examples/recognize-song.rs"

[dependencies]
shazamrs-core = { path = "vendor/shazamrs-core" }
reqwest = { version = "0.12", features = ["json", "gzip", "deflate"] }
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
thiserror = "1.0"
uuid = { version = "1.19.0", features = ["v4"] }
rand = "0.9.2"
